### ISSUE TITLE
Some themes fail to find `media.3d` categories in vivid 0.10

### ISSUE THREAD

**Issue by tranzystorekk** [sharkdp/vivid#136]
Environment details:

OS: Void Linux on WSL2
Shell: zsh `5.9`
Terminal: wezterm `20240520-135708-b8f94c47 x86_64-pc-windows-msvc`

Tested with a simple script:

```console
$ for theme in $(vivid themes); do if ! vivid generate ${theme} > /dev/null; then echo "${theme} failed!"; fi; done
Error: Could not find style for category 'media.3d.mesh'
dracula failed!
Error: Could not find style for category 'media.3d.mesh'
lava failed!
Error: Could not find style for category 'media.3d.mesh'
modus-operandi failed!
Error: Could not find style for category 'media.3d.mesh'
nord failed!
Error: Could not find style for category 'media.3d.application'
solarized-dark failed!
Error: Could not find style for category 'media.3d.application'
solarized-light failed!
Error: Could not find style for category 'media.3d.mesh'
tokyonight-moon failed!
Error: Could not find style for category 'media.3d.application'
tokyonight-night failed!
Error: Could not find style for category 'media.3d.application'
tokyonight-storm failed!
```

**Comment by sharkdp** [comment]
Oh — thank you for reporting that! I thought we had tests for those kind of basic checks. Should have been more careful when creating the release. Should be easy to fix hopefully.

**Comment by sharkdp** [comment]
Fixed; new release is out. Thanks again

**Comment by zmargeta** [comment]
Hi, this issue is unfortunately still reproducible on 0.10.1.

I am using fish shell and tokyonight-storm theme, and still randomly get either

Error: Could not find style for category 'media.3d.mesh'
Error: Could not find style for category 'media.3d.application'

**Comment by sharkdp** [comment]
Do you happen to have an old theme file lying around on your disk?

**Comment by zmargeta** [comment]
@sharkdp you are correct, it got left over on disk :)
